services:
  superlink:
    image: flwr/superlink:1.14.0
    container_name: superlink
    command:
      - --insecure
      - --isolation
      - process
    ports:
      - 9091:9091
      - 9092:9092
      - 9093:9093
    networks:
      - flwr-network
  
  supernode-1:
    image: flwr/supernode:1.14.0
    container_name: supernode-1
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --node-config
      - "partition-id=0 num-partitions=2"
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
    ports:
      - 9094:9094
    networks:
      - flwr-network
    depends_on:
      - superlink
  
  supernode-2:
    image: flwr/supernode:1.14.0
    container_name: supernode-2
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --node-config
      - "partition-id=1 num-partitions=2"
      - --clientappio-api-address
      - 0.0.0.0:9095
      - --isolation
      - process
    ports:
      - 9095:9095
    networks:
      - flwr-network
    depends_on:
      - superlink

  serverapp:
    build:                           
      context: .                     
      dockerfile: serverapp.Dockerfile
    image: multi_serverapp:0.0.1      
    container_name: serverapp            
    command:                         
      - --insecure
      - --serverappio-api-address
      - superlink:9091
    networks:
      - flwr-network
    depends_on:
      - superlink
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
  
  clientapp-1:
    build:                           
      context: .                     
      dockerfile: clientapp.Dockerfile
    image: multi_clientapp:0.0.1      
    container_name: clientapp-1
    command:                         
      - --insecure
      - --clientappio-api-address
      - supernode-1:9094
    networks:
      - flwr-network
    depends_on:
      - supernode-1
  
  clientapp-2:
    build:                           
      context: .                     
      dockerfile: clientapp.Dockerfile
    image: multi_clientapp:0.0.1      
    container_name: clientapp-2
    command:                         
      - --insecure
      - --clientappio-api-address
      - supernode-2:9095
    networks:
      - flwr-network
    depends_on:
      - supernode-2

networks:
  flwr-network:
    driver: bridge